version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "*" 
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
